language: node_js
node_js:
  - "node"
install:
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-core.git iotaeco/iota-pico-core
  - cd iotaeco/iota-pico-core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-data.git iotaeco/iota-pico-data
  - cd iotaeco/iota-pico-data
  - npm link @iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-crypto.git iotaeco/iota-pico-crypto
  - cd iotaeco/iota-pico-crypto
  - npm link @iota-pico/core @iota-pico/data
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-api.git iotaeco/iota-pico-api
  - cd iotaeco/iota-pico-api
  - npm link @iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-business.git iotaeco/iota-pico-business
  - cd iotaeco/iota-pico-business
  - npm link @iota-pico/core @iota-pico/data @iota-pico/api @iota-pico/crypto
  - npm link
  - cd ../iota-pico-storage
  - npm link @iota-pico/core @iota-pico/data @iota-pico/api @iota-pico/crypto @iota-pico/business
  - npm install
script:
  - npm run dist || travis_terminate 1
  - npm run security || travis_terminate 1
  - npm run test-publish || travis_terminate 1
cache:
  directories:
    - "node_modules"
